// <auto-generated />
using System;
using GYM_ITM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GYM_ITM.Migrations
{
    [DbContext(typeof(DbgymContext))]
    [Migration("20250426005142_CmabioUnoAMuchosEspacioHorarios")]
    partial class CmabioUnoAMuchosEspacioHorarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GYM_ITM.Models.Actividades", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<string>("DescripcionActividad")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreActividad")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdActividad")
                        .HasName("PK__Activida__5EAF86A40B737269");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("GYM_ITM.Models.Espacio", b =>
                {
                    b.Property<int>("IdEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspacio"));

                    b.Property<int?>("LimiteDisponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreEspacio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdEspacio")
                        .HasName("PK__Espacios__CA4C0889747AF17A");

                    b.ToTable("Espacios");
                });

            modelBuilder.Entity("GYM_ITM.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdActividad")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspacio")
                        .HasColumnType("int");

                    b.HasKey("IdHorario")
                        .HasName("PK__Horarios__1539229B93EFD8E6");

                    b.HasIndex("IdActividad");

                    b.HasIndex("IdEspacio");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("GYM_ITM.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF976F241567");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UsuarioHorario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdHorario")
                        .HasName("PK__UsuarioH__FA362DBEFC8EF197");

                    b.HasIndex("IdHorario");

                    b.ToTable("UsuarioHorario", (string)null);
                });

            modelBuilder.Entity("GYM_ITM.Models.Horario", b =>
                {
                    b.HasOne("GYM_ITM.Models.Actividades", "IdActividadNavigation")
                        .WithMany("Horarios")
                        .HasForeignKey("IdActividad")
                        .HasConstraintName("FK__Horarios__IdActi__4E88ABD4");

                    b.HasOne("GYM_ITM.Models.Espacio", "IdEspacioNavigation")
                        .WithMany("Horarios")
                        .HasForeignKey("IdEspacio")
                        .HasConstraintName("FK__Horarios__IdEspa__4F7CD00D");

                    b.Navigation("IdActividadNavigation");

                    b.Navigation("IdEspacioNavigation");
                });

            modelBuilder.Entity("UsuarioHorario", b =>
                {
                    b.HasOne("GYM_ITM.Models.Horario", null)
                        .WithMany()
                        .HasForeignKey("IdHorario")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioHo__IdHor__5535A963");

                    b.HasOne("GYM_ITM.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioHo__IdUsu__5441852A");
                });

            modelBuilder.Entity("GYM_ITM.Models.Actividades", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("GYM_ITM.Models.Espacio", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
